pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Fabric'
                    url = uri('https://maven.fabricmc.net')
                }
            }
            filter {
                includeGroupAndSubgroups('net.fabricmc')
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

String modId = providers.gradleProperty("mod_id").get()

rootProject.name = modId

rootDir.listFiles().findAll {
    it.isDirectory()
        && it.name != "buildSrc"
        && (new File(it, "build.gradle").exists() || new File(it, "build.gradle.kts").exists())
}.forEach {
    String relativePath = rootDir.toPath().relativize(it.toPath()).toString()
    String projectName = ":$modId-$relativePath"

    include(projectName)
    project(projectName).projectDir = it
}
