plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '7.0.0-beta.46'
}
base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}
//mixin {
//    config("${mod_id}.mixins.json")
//    config("${mod_id}.forge.mixins.json")
//}
jar {
    manifest {
        attributes["MixinConfigs"] = "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    }
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    // Automatically enable forge AccessTransformers if the file exists
    // This location is hardcoded in Forge and can not be changed.
    // https://github.com/MinecraftForge/MinecraftForge/blob/be1698bb1554f9c8fa2f58e32b9ab70bc4385e60/fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java#L123
    // Forge still uses SRG names during compile time, so we cannot use the common AT's
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        configureEach {
            args "-mixin.config=${mod_id}.mixins.json"
            args "-mixin.config=${mod_id}.forge.mixins.json"
        }

        client {
            workingDir = file('runs/client')
        }

        server {
            workingDir = file('runs/server')
        }

        data {
            workingDir = file('runs/data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    maven minecraft.mavenizer
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")

    // This is currently bugged due to the absence of obfuscation mappings
    //annotationProcessor "org.spongepowered:mixin:0.8.5-SNAPSHOT:processor"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
        }
    }
}
